name: "Deploy Website to CloudFront using S3 as origin using GitHub Actions"

on:
  push:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build Website
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
      - name: Copy the build folder to S3 bucket
        run: aws s3 sync ./build/. s3://www.elasticsi-project-bucket
      - name: Invalidating CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2OUY338AD11Y3 --paths "/*"