name: "Deploy Website to S3 using GitHub Actions"

on:
  push:
    branches: ["master", "develop"]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build Website
        run: npm run build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # - uses: ItsKarma/aws-cli@v1.70.0
      #   with: 
      - uses: aws s3 sync ./build/. s3://www.elasticsi-project-bucket
      # - name: Copy to S3    
      #   run: aws --version |
      - name: Invalidating CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E2ZEAE6OM42MO5 --paths "/*"